#!/usr/bin/env bash
# Display information for the domain and subdomain

display_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local record_type
    local destination
    
    destination=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $5}')
    record_type=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $4}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain=$1
subdomain=$2

if [ -z "$subdomain" ]; then
    display_subdomain_info "$domain" www
    display_subdomain_info "$domain" lb-01
    display_subdomain_info "$domain" web-01
    display_subdomain_info "$domain" web-02
else
    display_subdomain_info "$domain" "$subdomain"
fi