#!/usr/bin/env bash
# Install nginx web server

# Update package lists
apt-get update

# Install nginx web server
apt-get install -y nginx

# Ensure nginx is stopped
service nginx stop

# Create HTML page with "Hello World!"
echo "Hello World!" > /var/www/html/index.html

# Start nginx server
service nginx start