#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server active IPs

# Create symlink from a configuration file in sites-available to sites-enabled
# To ensure that nginx use the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
service nginx start