#!/usr/bin/env bash
# Nginx must be running, and listening on port 80 of all the server active IP
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
echo "nginx is not running" > /var/run/nginx.pid