#!/usr/bin/env bash

# Install UFW:
sudo apt update
sudo apt install ufw

# Set default incoming policy to deny:
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

# Enable ufw
sudo ufw enable

# Confirm
sudo ufw status verbose