#!/usr/bin/env bash

# Bash script that uses ssh to connect to your server using the private key
# ~/.ssh/school with the user ubuntu.

# Requirements:

# Only use ssh single-character flags
# You cannot use -l
# You do not need to handle the case of a private key protected by a passphrase

server="ubuntu@100.25.46.141"
private_key="~/.ssh/school"
ssh -i "$private_key" ubuntu@"$server"
